Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.boot_timeout = 600

  # --- Máquina Web ---
  config.vm.define "web" do |web|
    web.vm.hostname = "web-server"
    web.vm.network "private_network", ip: "192.168.56.20"

    web.vm.provider "virtualbox" do |vb|
      vb.name = "ca4-part2-web"
      vb.memory = 1024
      vb.cpus = 1
    end

    # Provisionamento com Ansible
    web.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision/playbook.yml"
      ansible.inventory_path = "provision/inventory"
      ansible.limit = "web"
    end
  end

  # --- Máquina DB ---
  config.vm.define "db" do |db|
    db.vm.hostname = "db-server"
    db.vm.network "private_network", ip: "192.168.56.21"

    db.vm.provider "virtualbox" do |vb|
      vb.name = "ca4-part2-db"
      vb.memory = 1024
      vb.cpus = 1
    end

    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision/playbook.yml"
      ansible.inventory_path = "provision/inventory"
      ansible.limit = "db"
    end
  end
end
